'use client'

import { useEffect, useState } from 'react'

const whatsappBase = 'https://wa.me/5511947256071'
const whatsapp = `${whatsappBase}?text=${encodeURIComponent('Olá! Vim pelo site da Barbearia DoGago e gostaria de agendar um horário.')}`
const clubWhatsapp = `${whatsappBase}?text=${encodeURIComponent('Olá! Vi o Clube DoGago no site e gostaria de saber mais sobre o plano de R$ 109,90.')}`
const instagram = 'https://www.instagram.com/barbearia_dogago/'
const maps = 'https://www.google.com/maps/search/?api=1&query=R.%20Conselheiro%20Moreira%20de%20Barros%2C%202511%20-%20Loja%207%20-%20Santana%2C%20S%C3%A3o%20Paulo'

const services = [
  ['Corte', 'R$ 60,00'], ['Barba', 'R$ 40,00'], ['Corte + Barba', 'R$ 90,00'], ['Progressiva', 'R$ 80,00'], ['Luzes', 'R$ 70,00'], ['Platinado', 'R$ 140,00'], ['Hidratação', 'R$ 20,00'], ['Limpeza facial', 'R$ 20,00'],
]
const extras = [['Luzes', 'R$ 63,00', 'R$ 70,00'], ['Platinado', 'R$ 126,00', 'R$ 140,00'], ['Hidratação', 'R$ 18,00', 'R$ 20,00'], ['Depilação na cera', 'R$ 27,00', 'R$ 30,00'], ['Relaxamento', 'R$ 18,00', 'R$ 20,00'], ['Desondulação dos fios', 'R$ 72,00', 'R$ 80,00'], ['Ozonioterapia', 'R$ 18,00', 'R$ 20,00'], ['Limpeza facial', 'R$ 18,00', 'R$ 20,00'], ['Sobrancelha', 'R$ 9,00', 'R$ 10,00'], ['Cone Hindu', 'R$ 36,00', 'R$ 40,00']]
const products = [['Pomada Pó', 'R$ 51,75', 'R$ 57,50'], ['Pomada Seco Médio', 'R$ 34,65', 'R$ 38,50'], ['Pomada Seco Alta', 'R$ 34,65', 'R$ 38,50'], ['Pomada Molhado Alta', 'R$ 34,65', 'R$ 38,50'], ['Balm Menta', 'R$ 58,95', 'R$ 65,50'], ['Minoxidil', 'R$ 90,00', 'R$ 100,00'], ['Shampoo Barba Menta', 'R$ 54,45', 'R$ 60,50'], ['Óleo de Barba Sândalo e Almíscar', 'R$ 72,00', 'R$ 80,00'], ['Laquê', 'R$ 45,00', 'R$ 50,00'], ['Balm Café e Baunilha', 'R$ 58,95', 'R$ 65,50'], ['Shampoo Café e Baunilha', 'R$ 54,45', 'R$ 60,50'], ['Balm Sândalo e Almíscar', 'R$ 58,95', 'R$ 65,50'], ['Shampoo Sândalo e Almíscar', 'R$ 54,45', 'R$ 65,50'], ['Óleo Café e Baunilha', 'R$ 76,50', 'R$ 85,00'], ['Leave-in', 'R$ 67,50', 'R$ 75,00'], ['Kit Minoxidil 8%', 'R$ 109,80', 'R$ 122,00'], ['Leave-in Teen', 'R$ 67,50', 'R$ 75,00'], ['Pomada Teen', 'R$ 34,65', 'R$ 38,50'], ['Pente de madeira', 'R$ 27,00', 'R$ 30,00'], ['Shampoo cabelo', 'R$ 58,50', 'R$ 65,00'], ['Condicionador cabelo', 'R$ 58,50', 'R$ 65,00']]
const gallery = ['https://images.unsplash.com/photo-1621605815971-fbc98d665033?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1622286342621-4bd786c2447c?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1599351431202-1e0f0137899a?auto=format&fit=crop&w=1000&q=85', 'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1000&q=85']

function Reveal({ children, className = '' }: { children: React.ReactNode; className?: string }) { return <div className={`reveal ${className}`}>{children}</div> }
function PriceRows({ rows, product = false }: { rows: string[][]; product?: boolean }) { return <div className={`price-rows ${product ? 'product-rows' : ''}`}>{rows.map(([name, price, old]) => <div className="price-row" key={name}><strong>{name}</strong><span>{old && <del>{old}</del>} {price}</span></div>)}</div> }

export default function Page() {
  const [menuOpen, setMenuOpen] = useState(false)
  const [scrolled, setScrolled] = useState(false)
  const [cursor, setCursor] = useState({ x: 0, y: 0, active: false })
  const [tilt, setTilt] = useState({ x: 0, y: 0 })

  useEffect(() => {
    const onScroll = () => setScrolled(window.scrollY > 48)
    const onMove = (event: MouseEvent) => { setCursor({ x: event.clientX, y: event.clientY, active: Boolean((event.target as HTMLElement)?.closest('a,button,.gallery-card,.hero-object')) }); setTilt({ x: (event.clientX / window.innerWidth - .5) * 10, y: (event.clientY / window.innerHeight - .5) * -7 }) }
    const observer = new IntersectionObserver((entries) => entries.forEach((entry) => entry.isIntersecting && entry.target.classList.add('is-visible')), { threshold: .12 })
    window.addEventListener('scroll', onScroll, { passive: true }); window.addEventListener('mousemove', onMove)
    document.querySelectorAll('.reveal').forEach((el) => observer.observe(el))
    return () => { window.removeEventListener('scroll', onScroll); window.removeEventListener('mousemove', onMove); observer.disconnect() }
  }, [])

  return <main>
    <div className="grain" aria-hidden="true" /><div className="custom-cursor" style={{ left: cursor.x, top: cursor.y }} data-active={cursor.active}>{cursor.active && <span>OPEN</span>}</div>
    <header className={`site-header ${scrolled ? 'is-scrolled' : ''}`}><a className="logo-lockup" href="#inicio" aria-label="Barbearia DoGago início"><small>BARBEARIA</small><b>DO<span>G</span>AGO</b><i>SANTANA · SP</i></a><nav className="desktop-nav" aria-label="Navegação principal"><a href="#sobre">SOBRE</a><a href="#servicos">SERVIÇOS</a><a href="#clube">CLUBE</a><a href="#contato">CONTATO</a></nav><a className="header-cta" href={whatsapp} target="_blank" rel="noreferrer">AGENDAR <span>↗</span></a><button className="menu-toggle" onClick={() => setMenuOpen(!menuOpen)} aria-label={menuOpen ? 'Fechar menu' : 'Abrir menu'} aria-expanded={menuOpen}><i /><i /></button></header>
    <div className={`mobile-menu ${menuOpen ? 'open' : ''}`}><p className="eyebrow">BARBEARIA CONTEMPORÂNEA · SANTANA</p>{[['início','inicio'],['sobre','sobre'],['serviços','servicos'],['clube','clube'],['contato','contato']].map(([label,id]) => <a key={id} href={`#${id}`} onClick={() => setMenuOpen(false)}>{label.toUpperCase()}</a>)}<a className="button button-bronze" href={whatsapp} target="_blank" rel="noreferrer">AGENDAR HORÁRIO <span>↗</span></a></div>

    <section id="inicio" className="hero"><div className="hero-image" /><div className="hero-overlay" /><div className="hero-copy"><Reveal><p className="eyebrow">ZONA NORTE · SÃO PAULO</p></Reveal><Reveal><h1>SEU ESTILO.<br /><em>NOSSO</em> TRABALHO.</h1></Reveal><Reveal><a className="button button-light" href={whatsapp} target="_blank" rel="noreferrer">AGENDAR HORÁRIO <span>↗</span></a><a className="hero-secondary" href="#servicos">CONHECER SERVIÇOS ↓</a></Reveal></div><div className="hero-object" style={{ transform: `translate3d(${tilt.x}px,${tilt.y}px,0) rotate(-18deg)` }} aria-hidden="true"><span>DG</span><div className="object-ring" /></div><div className="scroll-note">ROLE PARA EXPLORAR <span>↓</span></div></section>

    <section id="sobre" className="story section-pad"><Reveal><p className="eyebrow bronze">A CASA</p></Reveal><div className="story-grid"><Reveal><h2>UM LUGAR<br />PARA <span>VOCÊ.</span></h2></Reveal><Reveal className="story-text"><p className="lead">A Barbearia DoGago é um espaço para cuidar do visual, trocar uma ideia e sair daqui se sentindo bem.</p><p>Um endereço na Zona Norte onde técnica encontra proximidade. Onde o detalhe importa, o atendimento é leve e cada visita tem seu próprio ritmo.</p><a className="text-link" href={instagram} target="_blank" rel="noreferrer">CONHEÇA A DOGAGO <span>↗</span></a></Reveal></div></section>

    <section className="experience section-pad"><Reveal><p className="eyebrow bronze">A EXPERIÊNCIA</p><h2>DETALHE<br /><span>QUE FICA.</span></h2></Reveal><div className="experience-list">{['ESTILO','PRECISÃO','CUIDADO','ATENDIMENTO'].map((item) => <Reveal key={item}><div className="experience-row"><h3>{item}</h3><p>Os pequenos detalhes fazem a diferença.</p><b>↗</b></div></Reveal>)}</div></section>

    <section className="services section-pad" id="servicos"><Reveal><p className="eyebrow bronze">SERVIÇOS</p><div className="services-heading"><h2>SEU<br /><span>ESTILO.</span></h2><p>Cortes, barba e cuidados pensados para acompanhar a sua rotina.</p></div></Reveal><div className="service-layout"><div><h3 className="subheading">CORTES / SERVIÇOS</h3><PriceRows rows={services} /></div><div className="service-visual"><div className="service-visual-image" style={{ backgroundImage: `url(${gallery[0]})` }} /><span>DO GAGO EM CENA</span></div></div><div className="extras-block"><h3 className="subheading">EXTRAS <small>10% OFF NO CLUBE</small></h3><PriceRows rows={extras} /></div><a className="button button-bronze" href={whatsapp} target="_blank" rel="noreferrer">AGENDAR HORÁRIO <span>↗</span></a></section>

    <section className="club section-pad" id="clube"><div className="club-mark">DG</div><Reveal><p className="eyebrow">CLUBE DOGAGO</p><div className="club-heading"><div><h2>SEU ESTILO.<br /><em>SEMPRE</em><br />EM DIA.</h2><p className="club-copy">O plano mensal para transformar o cuidado com cabelo e barba em parte da rotina.</p></div><div className="club-price"><strong>R$ 109,90</strong><span>por mês</span></div></div></Reveal><div className="club-grid"><div><p className="subheading dark">BENEFÍCIOS DO PLANO</p>{[['CORTE','R$ 60,00'],['PEZINHO','R$ 20,00'],['RASPAR NA MÁQUINA','R$ 30,00']].map(([name,old]) => <div className="benefit" key={name}><div><strong>{name}</strong><span>100% OFF</span></div><p><del>De {old}</del><b>Por R$ 0,00</b></p></div>)}<div className="club-note">Serviços extras com <b>10% OFF</b><br />Agenda liberada com 15 dias de antecedência.</div></div><div><p className="subheading dark">INFORMAÇÕES</p><p className="club-note">Corte, pezinho e raspar na máquina gratuitos dentro das condições do plano.</p><p className="club-note">Para alteração ou cancelamento do plano, por favor, entre em contato com a recepção.</p><a className="button button-dark" href={clubWhatsapp} target="_blank" rel="noreferrer">QUERO CONHECER O CLUBE <span>↗</span></a></div></div></section>

    <section className="products section-pad"><Reveal><p className="eyebrow bronze">PRODUTOS</p><div className="products-heading"><h2>COSMÉTICOS<br /><span>DA CASA.</span></h2><p>Uma extensão da experiência DoGago. Valores já com 10% de desconto.</p></div></Reveal><div className="products-layout"><div className="product-feature"><div className="product-placeholder">DG</div><p>SELEÇÃO DOGAGO</p><h3>Cuidados para<br />continuar em casa.</h3></div><div><PriceRows rows={products} product /></div></div></section>

    <section className="gallery section-pad"><Reveal><p className="eyebrow bronze">A GALERIA</p><h2>FEITO PARA<br /><span>SER VISTO.</span></h2></Reveal><div className="gallery-grid">{gallery.map((image,index) => <Reveal key={image} className={`gallery-card card-${index+1}`}><div className="gallery-image" style={{ backgroundImage: `url(${image})` }} /><span>{['CORTE','BARBA','DETALHES','AMBIENTE'][index]}</span></Reveal>)}</div></section>

    <section className="testimonials section-pad" id="avaliacoes"><Reveal><p className="eyebrow bronze">QUEM CONHECE</p><h2>QUEM CONHECE,<br /><span>VOLTA.</span></h2></Reveal><div className="rating"><strong>5,0</strong><span>★ GOOGLE</span></div><div className="quotes">{['Muito bom, ambiente agradável, os meninos são gente boa demais.','Meu filho adorou o dono da barbearia Lucas e o atendimento é muito bom.','Melhor barbearia da Zona Norte e região.'].map((quote) => <Reveal key={quote}><blockquote>“{quote}”</blockquote></Reveal>)}</div></section>
    <section className="location section-pad"><Reveal><p className="eyebrow bronze">ONDE ESTAMOS</p><h2>ZONA NORTE.<br /><span>SÃO PAULO.</span></h2></Reveal><div className="location-grid"><div><p className="lead">R. Conselheiro Moreira de Barros, 2511 - Loja 7<br />Santana, São Paulo - SP<br />02430-001</p><a className="text-link" href={maps} target="_blank" rel="noreferrer">COMO CHEGAR <span>↗</span></a></div><div className="map-card"><span>SANTANA<br /><b>02430-001</b></span><i /></div></div></section>
    <section className="contact section-pad" id="contato"><Reveal><p className="eyebrow">A PRÓXIMA CONVERSA</p><h2>VAMOS<br /><em>MARCAR?</em></h2><a className="contact-link" href={whatsapp} target="_blank" rel="noreferrer">(11) 94725-6071 <span>↗</span></a><p>@barbearia_dogago</p></Reveal></section>
    <footer><div className="footer-top"><p className="eyebrow bronze">BARBEARIA DOGAGO</p><h2>SEU PRÓXIMO CORTE<br /><span>COMEÇA AQUI.</span></h2><a className="button button-bronze" href={whatsapp} target="_blank" rel="noreferrer">AGENDAR HORÁRIO <span>↗</span></a></div><div className="footer-bottom"><a className="logo-lockup" href="#inicio"><small>BARBEARIA</small><b>DO<span>G</span>AGO</b></a><p>R. Conselheiro Moreira de Barros, 2511 - Loja 7 · Santana - São Paulo/SP</p><a href={instagram} target="_blank" rel="noreferrer">@barbearia_dogago ↗</a></div></footer><a className="floating-whatsapp" href={whatsapp} target="_blank" rel="noreferrer" aria-label="Agendar pelo WhatsApp">WHATSAPP <span>↗</span></a>
  </main>
}
