"use client";

import Carousel from "@/components/Carousel";
import { ArrowIcon } from "@/components/ArrowIcon";
import { Reveal, Rows } from "@/components/common";
import { address, booking, clubLink, clubSlides, gallery, extras, links, products, reviews, services } from "@/data/siteData";

export function Hero({ tilt }) { return <section id="inicio" className="hero"><div className="hero-image" /><div className="hero-overlay" /><div className="hero-copy"><Reveal><h1>SEU ESTILO.<br /><em>NOSSO</em> TRABALHO.</h1></Reveal><Reveal><a className="button button-light" href={booking} target="_blank" rel="noreferrer">AGENDAR HORÁRIO <ArrowIcon /></a><a className="hero-secondary" href="#servicos">CONHECER SERVIÇOS <ArrowIcon direction="down" /></a></Reveal></div><div className="hero-object" style={{ transform: `translate3d(${tilt.x}px,${tilt.y}px,0) rotate(-18deg)` }}><span>DG</span><div className="object-ring" /></div><div className="scroll-note">ROLE PARA EXPLORAR</div></section>; }

export function About() { return <section id="sobre" className="story section-pad"><Reveal><p className="eyebrow bronze">A CASA</p></Reveal><div className="story-grid"><Reveal><h2>UM LUGAR<br />PARA <span>VOCÊ.</span></h2></Reveal><Reveal className="story-text"><p className="lead">A Barbearia DoGago é um espaço para cuidar do visual, trocar uma ideia e sair daqui se sentindo bem.</p><p>Um endereço na Zona Norte onde técnica encontra proximidade. Onde o detalhe importa, o atendimento é leve e cada visita tem seu próprio ritmo.</p><a className="text-link" href={links.instagram} target="_blank" rel="noreferrer">CONHECER <ArrowIcon /></a></Reveal></div></section>; }

export function Services() { return <section id="servicos" className="services section-pad"><Reveal><p className="eyebrow bronze">SEU ESTILO</p><div className="services-heading"><h2>CUIDADO<br /><span>NO PONTO.</span></h2><p>Preços públicos e transparentes. Membros do Clube DoGago têm 10% OFF nos serviços extras elegíveis.</p></div></Reveal><div className="service-layout"><div><h3 className="subheading">CORTES / SERVIÇOS</h3><Rows rows={services} /></div><div className="service-visual"><div className="service-visual-image" style={{ backgroundImage: `url(${gallery[0]})` }} /><span>DO GAGO EM CENA</span></div></div><div className="extras-block"><h3 className="subheading">EXTRAS</h3><Rows rows={extras} /></div><a className="button button-bronze" href={booking}>AGENDAR HORÁRIO <ArrowIcon /></a></section>; }

export function Products() { return <section id="produtos" className="products section-pad"><Reveal><p className="eyebrow bronze">PRODUTOS</p><div className="products-heading"><h2>PARA LEVAR<br /><span>A CASA.</span></h2><p>Valores cheios para o público. Membros do Clube DoGago têm 10% OFF em cosméticos.</p></div></Reveal><div className="products-layout"><div className="product-feature"><div className="product-placeholder">DG</div><p>SELEÇÃO DOGAGO</p><h3>Cuidados para<br />continuar em casa.</h3></div><Rows rows={products} product /></div></section>; }

export function Club() { return <section id="clube" className="club section-pad"><Reveal><p className="eyebrow">CLUBE DOGAGO</p><div className="club-heading"><div><h2>SEU ESTILO<br /><em>EM DIA.</em></h2></div></div></Reveal><Carousel className="club-carousel" variant="portrait" items={clubSlides.map((src, index) => ({ src, id: `clube-${index}` }))} label="Prints do Clube DoGago" previousLabel="Print anterior" nextLabel="Próximo print" slideClassName="club-slide" viewportClassName="club-track" renderItem={(item, index) => <img src={item.src} alt={`Informações do Clube DoGago, slide ${index + 1} de ${clubSlides.length}`} draggable="false" />} /><a className="button button-dark club-cta" href={clubLink} target="_blank" rel="noreferrer">QUERO CONHECER O CLUBE <ArrowIcon /></a></section>; }

export function Gallery() { return <section id="galeria" className="gallery section-pad"><Reveal><p className="eyebrow bronze">GALERIA</p><h2>FEITO PARA<br /><span>SER VISTO.</span></h2></Reveal><Carousel variant="square" items={gallery.map((src, index) => ({ src, id: `galeria-${index}`, label: ["CORTE", "BARBA", "DETALHES", "AMBIENTE"][index] }))} label="Galeria de imagens da Barbearia DoGago" previousLabel="Imagem anterior" nextLabel="Próxima imagem" slideClassName="gallery-frame" viewportClassName="gallery-track" renderItem={(item) => <><div style={{ backgroundImage: `url(${item.src})` }} /><span>{item.label}</span></>} /></section>; }

export function Testimonials() { return <section id="quem-conhece" className="testimonials section-pad"><Reveal><p className="eyebrow bronze">QUEM CONHECE</p><h2>O QUE NOSSOS<br /><span>CLIENTES DIZEM.</span></h2></Reveal><div className="rating"><strong>5,0 ★</strong><span>GOOGLE</span></div><Carousel className="review-carousel" variant="testimonials" items={reviews.map(([name, text]) => ({ name, text, id: name }))} label="Avaliações de clientes" previousLabel="Avaliação anterior" nextLabel="Próxima avaliação" slideClassName="review-card" viewportClassName="review-viewport" renderItem={(item) => <article><span className="review-mark">“</span><div className="review-stars" aria-label="5 estrelas">★★★★★</div><blockquote>{item.text}</blockquote><p><strong>{item.name}</strong><span>AVALIAÇÃO DE CLIENTE</span></p></article>} /></section>; }

export function Location() { return <section id="onde-estamos" className="location section-pad"><Reveal><p className="eyebrow bronze">ONDE ESTAMOS</p><h2>ZONA NORTE.<br /><span>SÃO PAULO.</span></h2></Reveal><div className="location-grid"><div><p className="lead">{address}</p><p className="phone">(11) 94725-6071</p><a className="text-link" href={links.maps} target="_blank" rel="noreferrer">COMO CHEGAR <ArrowIcon /></a></div><div className="map-card"><span>SANTANA<br /><b>02430-001</b></span><i /></div></div></section>; }

export function Contact() { return <section id="contato" className="contact section-pad"><Reveal><p className="eyebrow bronze">BARBEARIA DOGAGO</p><h2>SEU PRÓXIMO CORTE<br /><em>COMEÇA AQUI.</em></h2><p>Agende seu horário com a Barbearia DoGago.</p></Reveal><a className="button button-bronze" href={booking}>AGENDAR HORÁRIO <ArrowIcon /></a></section>; }
